### ISSUE TITLE
automatically delete entries after a fixed amount of time

### ISSUE THREAD

**Issue by Pranav2612000** [Pranav2612000/milaap#134]
There is some data that needs to be automatically cleared after a fixed amount of time. This includes:- 
1) Inactive participants in the online array of a room
2) Inactive guest participants in the room's member list
3) sessions and other login credentials of guest users
<strike>4) Messages sent on the group chat(To be discussed)</strike>

MongoDB has a feature (TTL) to automatically delete data after a fixed amount of time. We can use the feature to fix this issue

**Comment by AnupNair08** [comment]
Fixed in #142
