### ISSUE TITLE
'Delete Room' option to users

### ISSUE THREAD

**Issue by naman-modi** [Pranav2612000/milaap#143]
We definitely need this feature which will give user, that is 'admins' the option to delete the room.

Once the 'Delete Room' is clicked:
- All the users and room should be deleted
- All the messages in that room should be deleted.

**Comment by yashshah1** [comment]
I have a query, how are admins denoted in the database?
As far as I could tell, in the rooms collection, all users present in the `users` array are the admins of the room, so all of them must have the functionality, right?

**Comment by yashshah1** [comment]
I've added the backend for this feature in 72ec18a1433dee. I need some help as to where we can place the button in the UI, and whether or not to conditionally show it.

The backend takes care of whether the user is the admin or not.

For the front end, a possible roadmap is:
- The backend route that serves the details of the room can also add a flag next to each user (I'm not sure if this is already done) denoting whether or not he's an admin or not.
- Conditionally render a button to delete the room if that flag is true
- Hit the route and on success redirect him to the homepage

**Comment by Pranav2612000** [comment]
> I have a query, how are admins denoted in the database?
> As far as I could tell, in the rooms collection, all users present in the `users` array are the admins of the room, so all of them must have the functionality, right?

Yes.

**Comment by Pranav2612000** [comment]
Yup. I think the approach works. We could add a flag next to each room in the users table denoting if he's an admin of the room or a guest. Where do you plan on rendering the "Delete room" button?

**Comment by naman-modi** [comment]
"Delete Room" functionality can be similar to "Invite" functionality visible only to admins. 

>  We could add a flag next to each room in the users table denoting if he's an admin of the room or a guest.
From UI point of view, there's no need for this, as for now, only the rooms which the user is an admin of is displayed on the left sidebar.

I think delete room can be rendered with all other elements only, as the user can delete whenever he/she wants to delete it.

**Comment by yashshah1** [comment]
> From UI point of view, there's no need for this, as for now, only the rooms which the user is an admin of is displayed on the left sidebar.
Yes, but to render the button "Delete", the component will need some flag denoting whether or not the user has permissions.

@Pranav2612000 take a look at 21cf0140c098389, this should cover what we spoke about.

I'll start working on the UI tomorrow.

**Comment by Pranav2612000** [comment]
If the room is present in the rooms' array in the users' table, then the user is an admin of the room. The guest rooms he visits are not stored here.
