### ISSUE TITLE
fix: creating a new room doesnt update ui to display new room in rooms sidebar

### ISSUE THREAD

**Issue by Pranav2612000** [Pranav2612000/milaap#150]
Go to Dashboard & create a new room. On creating the room, you need to refresh the page to see the new room. The user should not need to refresh to see the room added( or automatically refresh for now).

**Comment by naman-modi** [comment]
This is fixed right?

**Comment by Pranav2612000** [comment]
Currently, we are using a very naive approach of automatically reloading the page, when new entry is successfully added. We should instead do it in a more React way

**Comment by naman-modi** [comment]
Right.

**Comment by vasusharma7** [comment]
Fixes #162
