### ISSUE TITLE
When user enters a room via url which does not exist, need to show an error

### ISSUE THREAD

**Issue by naman-modi** [Pranav2612000/milaap#156]
If a logged in user directly types in a url: ***/rooms/iyabdiybsa***,  for a room which does not exist we need to show an error.

Right now, it takes to that page, but since there is no entry in the database for that room, connections might not be established.

**Comment by AnupNair08** [comment]
Fixed this in #161 
Please review

**Comment by AnupNair08** [comment]
fixed in #163
