### ISSUE TITLE
fix: Title of the room

### ISSUE THREAD

**Issue by savannahar68** [Pranav2612000/milaap#160]
Fix the title of the room

Should be fixed at the top and will stay there even if scrolled. There should be no gap

Or other alternative is to keep the tittle and the time at the top itself

![image](https://user-images.githubusercontent.com/20986069/87758322-dde1d280-c829-11ea-8af7-4941dbea0a83.png)

@vasusharma7 assigning it to you

**Comment by vasusharma7** [comment]
Fixes #162 
Please check if it looks fine !
