### ISSUE TITLE
Code Cleanup + Removal of warnings

### ISSUE THREAD

**Issue by yashshah1** [Pranav2612000/milaap#173]
Proposed changes:
- Remove await / then chains
- Remove useless console logs
- Remove extra calls to bind
- Replace callbacks with await functions: [example](https://github.com/Pranav2612000/milaap/blob/master/backend/routes/room.js#L59)

Open to suggestions.

**Comment by veddandekar** [comment]
Could you make these changes and submit a PR for this?
It would be of great help.
