### ISSUE TITLE
URLs in text messages

### ISSUE THREAD

**Issue by yashshah1** [Pranav2612000/milaap#177]
Currently, when a sent message contains a URL, the message that is pushed on to the database has markup.
See: https://github.com/Pranav2612000/milaap/blob/master/src/views/Compose/index.js#L38
![image](https://user-images.githubusercontent.com/31387795/87877050-b477a100-c9f9-11ea-8dab-d0d3a0769f49.png)

This has multiple drawbacks
- Increases space taken up by DB
- (Minor): Increases query size to push to DB
- Makes the API unusable for future extension, as fetches from the database return HTML, when only the _message_ is requried

### Propopsal
Instead of pushing markup to database, run `urlify` when rendering messages in the chat, so that links are rendered on the front end, which enables only text to be pushed on to the database

**Comment by AnupNair08** [comment]
@yashshah1 
Thanks for suggesting the improvement. Changing to the proposed design.

**Comment by AnupNair08** [comment]
Fixed in #178.
Please review.
Change from the previous version on the db: 
![chk](https://user-images.githubusercontent.com/54449305/87878027-5d74ca80-c9ff-11ea-971b-1e210fac4ab0.png)
