### ISSUE TITLE
Remove unnecessary backend calls on dashboard

### ISSUE THREAD

**Issue by veddandekar** [Pranav2612000/milaap#19]
STR:
- Do a fresh login or tap on dashboard on left top once logged in.
- Check browser console.

I suspect that this is because calls are being made to backend when user is not in any room.

To-do: Prevent front-end from making calls when not in a room.

**Comment by veddandekar** [comment]
@vasusharma7 since you are already working with backend to improve messaging, I think this will be a simple fix for you

**Comment by vasusharma7** [comment]
Yes, I will take up this.

**Comment by vasusharma7** [comment]
See PR https://github.com/Pranav2612000/milaap/pull/47
