### ISSUE TITLE
Write a common endpoint to get all information regarding the room

### ISSUE THREAD

**Issue by Pranav2612000** [Pranav2612000/milaap#22]
Whenever a user enters a room, seperate backend calls are made to get messages, members, online members etc. Write a unified backend api which returns all this information - messages, group members, is there a ongoing call etc. 

Call this api when user enters a room, and store the request in state, to be used later.
Handle errors, if the call fails may be due to internet connectivity.

**Comment by Pranav2612000** [comment]
@AnupNair08, Would you like to work on this?

**Comment by AnupNair08** [comment]
Alright I'll work on it👍

**Comment by naman-modi** [comment]
@Pranav2612000 Is this still required?
As we were having talks to make APIs for feasibility?

@savannahar68 Any thoughts?

**Comment by savannahar68** [comment]
@naman-modi not for feasibility but to reduce overhead.

But I guess separate APIs are better for many reasons as we can use them in future somewhere else. Also getting all the members and chat can take a lot of time causing user to wait longer which is not a good thing.

@Pranav2612000 Do you agree?

Or another alternative to this is combine all the api's and then use GraphQl maybe?
@yashshah1 any thoughts about this

**Comment by Pranav2612000** [comment]
I think, Currently, it uses a single call to fetch room participants, room messages & online members. We can change that to separate calls if we want to make the "enter room" process faster.

**Comment by yashshah1** [comment]
@savannahar68 Adding GraphQL might be a greater overhead assuming that the data transmitted isn't very big in the first place (<500KB).

**Comment by Pranav2612000** [comment]
Closing this because I feel the current implementation works for now. Feel free to open this in the future.
