### ISSUE TITLE
Add feedback messages to login and signup pages

### ISSUE THREAD

**Issue by Pranav2612000** [Pranav2612000/milaap#24]
when user signups/ logins, not alerts/ popups are displayed, to give feedback to the user. Add proper alerts. 
Also, redirect to login page on successful signup.

**Comment by naman-modi** [comment]
I have made the following flow diagram for signing in.

@Pranav2612000 @veddandekar @AnupNair08 @vasusharma7 
Please have a look at this and approve it, and suggest changes if required.

![Signinflow](https://user-images.githubusercontent.com/38180263/82183998-8d6ef700-9904-11ea-9e12-519ae3a35c85.jpg)

**Comment by Pranav2612000** [comment]
If this is the first time signing in using google, ask for a username to associate with the account.

**Comment by naman-modi** [comment]
Okay. @AnupNair08 We will have to handle this. 
When the user for the first time signs in through google, need to ask for a username.

**Comment by vasusharma7** [comment]
See PR https://github.com/Pranav2612000/milaap/pull/47

**Comment by veddandekar** [comment]
Closing this one as the specific issue is fixed. The discussion related to Google authentication can be continued on the respective thread.
