### ISSUE TITLE
right-sidebar: styling of selected-list icon different from other tabs

### ISSUE THREAD

**Issue by Pranav2612000** [Pranav2612000/milaap#33]
![image](https://user-images.githubusercontent.com/20909078/82159867-0b081800-98af-11ea-8512-18d38e1c285d.png)

![image](https://user-images.githubusercontent.com/20909078/82159874-1b1ff780-98af-11ea-809b-70456afceddd.png)

@veddandekar - I think it will be very easy for you to fix

**Comment by veddandekar** [comment]
So do we want it different from the current blue highlight or should I just fix the same to work on the leftmost tab(as it currently does not) ?
