### ISSUE TITLE
database: Prevent users from creating already taken username.

### ISSUE THREAD

**Issue by Pranav2612000** [Pranav2612000/milaap#37]
No checks are in place to prevent users from taking already taken usernames. Provide proper response from the backend and display appropriate messages to users

**Comment by naman-modi** [comment]
- What about the users who will sign in using ***Google***?
- What kind of change required in the database for them?
- Will those signing in through google be allowed to select a separate username?

Do we need to add an avatar for the users? (designing features)

@Pranav2612000 @veddandekar @AnupNair08 @vasusharma7 
Need to discuss this.

**Comment by veddandekar** [comment]
If a person signs in using Google, he will still be asked to select a username. we could pre-fill the field with his Google id but he can definitely change that and choose a username completely unrelated to his email, if he wants to do so.

Allowing Google sign-in wise, I think the only change required in the DB will be the addition of Google auth string along with the existing user details.

Oh, and avatars or generic dp would be a nice (and necessary) addition.

**Comment by naman-modi** [comment]
Yes, I have kept those in mind and put a flow diagram in issue #24. 
Closing this issue, as is similar to #24
