### ISSUE TITLE
Redirect to dashboard on successful login

### ISSUE THREAD

**Issue by veddandekar** [Pranav2612000/milaap#4]
Currently fails to redirect.

**Comment by Pranav2612000** [comment]
Always works the second time. My guess is something to do with state and the username not being updated to localstorage, before the redirect. May investigate this tonight.

**Comment by Pranav2612000** [comment]
Vasu is working on this.

**Comment by vasusharma7** [comment]
The issue is resolved.

**Comment by veddandekar** [comment]
Thanks @vasusharma7
