### ISSUE TITLE
Stream continuing if user logs out directly

### ISSUE THREAD

**Issue by AnupNair08** [Pranav2612000/milaap#40]
Both video and screen streams continue to run if a peer directly logs out without stopping the stream
![issue](https://user-images.githubusercontent.com/54449305/82200160-4ee53680-991c-11ea-8571-5977f1b308c5.png)

**Comment by naman-modi** [comment]
Is it fixed in another branch?

**Comment by Pranav2612000** [comment]
Does the same happen on refresh?
Does the same happen on changing rooms?

**Comment by Pranav2612000** [comment]
> Is it fixed in another branch?

All changes have been merged to master, so its unlikely.

**Comment by veddandekar** [comment]
Nice find @AnupNair08 
Surprising issue indeed.
