### ISSUE TITLE
Create only two media objects per user

### ISSUE THREAD

**Issue by veddandekar** [Pranav2612000/milaap#5]
One for screen, one for video. When new user joins, send same object.

**Comment by Pranav2612000** [comment]
Please describe in detail. I think this has already been implemented.

**Comment by veddandekar** [comment]
For every new connection, are we using a single media stream object or has that already been changed ?

**Comment by Pranav2612000** [comment]
We get the media stream object from the user once, and the same object is sent to multiple peers. Does this solve the issue?

**Comment by veddandekar** [comment]
Does it allow creating one for video and one for screen?
Most apps do not allow this. But I do not see a reason why. We can definitely allow the user to be sharing both at once, if he/she chooses to do so.

**Comment by Pranav2612000** [comment]
Yes. Tested with modi yesterday

**Comment by veddandekar** [comment]
Perfect!
