### ISSUE TITLE
Implement reordering of video list

### ISSUE THREAD

**Issue by veddandekar** [Pranav2612000/milaap#6]
Support drag and drop on receiving video list.
Currently static.

**Comment by Pranav2612000** [comment]
https://github.com/atlassian/react-beautiful-dnd
@veddandekar  This has ready-made horizontal drag-drop lists. I have worked with this. It is a good library.

**Comment by veddandekar** [comment]
As it turns out, drag and drop libraries suffer performance issues even on images. Trying to make them work on videos turned out very shaky.
If anyone wants to try and tackle this one in their free time, feel free to do so.
